### ISSUE TITLE
Non-compliant with Framework folder structure

### ISSUE THREAD

**Issue by mrgwilliam** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#10]
This mission is currently not compliant with folder structure set forth by the 23rd Framework.

**Comment by rasolercrespo** [comment]
@mrgwilliam, can I get a tag when this is done so I may start Ops construction?

**Comment by AJCStriker** [comment]
The mission is intentionally not based on the framework. It is ready for base build.

**Comment by mrgwilliam** [comment]
@AJCStriker is there proper reason for not using the framework? The framework could be modified to accommodate but intentionally staying away from it will lead to inconsistency within previous and future operations. 

Also if your excuse it that it's not compatible, the scripts included would not cause an issue.

**Comment by AJCStriker** [comment]
The framework is unnecessary for this application. It contains several scripts, if not the majority of scripts that are not needed and does not provide a benefit to this operation.

As each operation is a bespoke development, there is no need or requirement to use the framework here nor a particular benefit to be gained from consistency. Particularly where it may lead to errors or undesirable inherited functionality. At this point the base of this operation is already underway and there is likely few benefits to be gained. 

If you wish to remedy this problem you may present a pull request that you believe solves this issue, in accordance with the branching model defined.

**Comment by mrgwilliam** [comment]
There is a bit of truth in your statement however completely disregarding an established model not not an effective means to an end. Scripts which are no longer used or effective should have been removed via established procedure.

Our framework has a good track record and should be improved not thrown away.

I'll deal with folder integration and framework adoption. It can be done without any effect on service/product if done correctly.

**Comment by AJCStriker** [comment]
Please ensure that you remove the following components:
* ZBE Cache
* View Distance Script
* Aeroson Player markers

Also make sure to follow the branching model and place a pull request so as to allow peer review.
