### ISSUE TITLE
WARNO

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#13]
@23rd-gaming-division/s3-plans needs to put together a WARNO based on #2 and #9. We should use this thread to iron out any additional details that the WARNO would require such as specialist equipment and the overarching plan of the operation.

**Comment by Oges03** [comment]
Once my game comes back online I'll look at the current build to get a feel for the blufor and redfor situation

**Comment by rasolercrespo** [comment]
Published today, and so the issue is closed.
