### ISSUE TITLE
Position the LHD

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#14]
We need to find a reasonable piece of ocean that is a substantial distance from the shore to prevent anti-ship fires. It also needs to be within shallow enough ocean to support the deployment of Mk11 Landing Craft.

The LHD could also be accompanied by a small fleet of maybe one LPD and potentially one destroyer?

**Comment by Heintz11** [comment]
I would say no more than 5km off shore

**Comment by AJCStriker** [comment]
I think that is a good maximum. The question is what do we reckon the blind fire range of anti ship weaponry is in ARMA? I think 3KM should be a good range from the target and we have to be careful that they do not have any weapon systems with a longer range. IE self propelled artillery.

**Comment by Heintz11** [comment]
True but with the artillery they would need a good spot first off and the only true anttiship tthatt there is in arms is the at launchers.

**Comment by AJCStriker** [comment]
The first rule of ARMA: Never doubt the level of retard or genius that AI are able to express.

**Comment by rasolercrespo** [comment]
^ This. I think 3 KM is fine, honestly.

**Comment by Oges03** [comment]
I've seen the AI place accurate unspotted IDF on targets across the map of Altis.  That said, their detection range should not hit us out at 3K.

**Comment by Heintz11** [comment]
And to that I would have to refer to striker's first rule of arma

**Comment by Heintz11** [comment]
And could we push the op up a day

**Comment by rasolercrespo** [comment]
We've decided to place the LHD at 001032 in Panthera. We're closing this issue.
