### ISSUE TITLE
Enemy faction

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#15]
So, we need to decide on our enemy. I am all for trying to fight the Russian (take away the 1-hit kill of Insurgent pack) and making it a little more militaristic. This also opens the possibility for the Russians trying to ACTUALLY have some more firepower in their hand (tanks, BMP, etc) without detracting realism.

It could be something like a "extremist" militaristic group of Russian militia who has broken off, and is seeking to implement a "Soldier Haven" in Panthera Island by opressing or recruiting the civies who live there already.

Fire away other ideas.

**Comment by AJCStriker** [comment]
I thought a cool idea might be if Panthera is an Eastern European / Soviet Bloc state that underwent a communist / ultranationalist revolution and has gained equipment through Russian aid.

We could have the desert region in the south as another country if we wanted to fight insurgents again.

I agree that Russians should be used to give a bit more kick, but let's make triple sure they are thicker than a plank nailed to a cinderblock.

**Comment by AJCStriker** [comment]
Also we would need some input from @Oges03 and Toler about whether Spartans is up to dealing with tanks yet. I think we might need to wait on the platoon to grow a little first.

**Comment by rasolercrespo** [comment]
That's fine with me. I just would find it weird having Eastern Rebels or Pirates with heavy armor or specialized equipment. But yes, I think we are sort of on the same page regarding what troops to use.

We can mix Eastern Rebels with Russian as needed. Does that sound fair, as opposed to going pure Russian or pure Eastern?

**Comment by AJCStriker** [comment]
I think this is something to consult @Oges03 on but I would say mixing the two would work pretty well.

**Comment by Oges03** [comment]
we don't have heavy anti-armor capability.  The WPN SQD would have the JAVs, and we only cary AT-4s which are ok against light and some medium armor, but pretty much bounce off anything else.

I'd request that we keep the threat forces to a minimum.  No more than 2-3 Squads dismounts and 1-2 mounted.  Also maybe a BMP type capability.  I'm all about a challenge, but tanks are a stretch right now.

**Comment by rasolercrespo** [comment]
@Oges03 -- not for this one or the close future, but having Russians would allow for that. Which of the following do you prefer?

- Only russians
- Only east european rebels
- A mix of both

**Comment by rasolercrespo** [comment]
We're going to experiment with all three, but potentially we're thinking of using a mix of both. We intend  to place rebels in the town and russian armed forces in the bases. Thus, we're closing this issue.
