### ISSUE TITLE
Place LHD + Friendly Base Troops

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#17]
This needs to be handled ASAP.

**Comment by rasolercrespo** [comment]
The LHD has been placed, and work is underway for this issue. @AJCStriker and myself are doing some work on this area, and we'll probably want @mrgwilliam, @Oges03 and @Zoosterbaan to verify our work.

**Comment by Oges03** [comment]
I can't get the mission to load; getting an error.  It don't say anything just program failed to start error when i run the gethub sync.  I'll play around with it and try to get it to work

**Comment by AJCStriker** [comment]
@Oges03 whats the problem?

**Comment by rasolercrespo** [comment]
@Zoosterbaan -- you should go ahead and set down the choppers and things your Airframe needs. I'll leave this one up to you.

**Comment by AJCStriker** [comment]
This is now complete.
