### ISSUE TITLE
Decide location for insertion

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#2]
The location needs to be:

1) Near an airfield
2) Near a water body
3) Defensible and seizable by a relatively small taskforce.

EDIT: Based on the new discussion, we will now drop on a town and not on an airfield.

**Comment by rasolercrespo** [comment]
@Zoosterbaan and myself will take care of this issue.

**Comment by AJCStriker** [comment]
I was looking at the unimproved runway and ATC area on Vatra at *02700219* for the FOB location.

There is a town, Valkova, at *022023* which could serve as a nice objective, particularly the military compound at *021025*. That military objective has a nice airborne LZ at *021024* and could lead to a second assualt on the military compound at *020021*. All this would give the Spartan's good time to clear Valkova and get Anvil into the unimproved airfield and begin building.

**Comment by AJCStriker** [comment]
# Recon shots of the Landing Sites
** Area overview: **

!(Area Overview)[http://cloud-4.steamusercontent.com/ugc/31856754839506586/71B243F4E0E65FAC085371124B62EE823F40EB55/2048x1152.resizedimage]

**LZ Area:**

!(LZ Area)[http://cloud-4.steamusercontent.com/ugc/31856754839508602/9554E9F56B7CA126293D27B0560C30026EA4A446/2048x1152.resizedimage]

**Unimproved Airfield:**

!(Airfield)[http://cloud-4.steamusercontent.com/ugc/31856754839507506/7D709868A464522DE27AA2F119341189CD799237/2048x1152.resizedimage]

**Comment by Heintz11** [comment]
![arma 3-01-11-2015 21-04-55](https://cloud.githubusercontent.com/assets/10492590/5698560/d3c90c92-99d5-11e4-9f03-77f546f66c23.jpg)
Possible FOB setup, courtesy of charlie company

**Comment by AJCStriker** [comment]
@Heintz11 The FOB setup looks great! You should definitely add a roadblock on the MSR at the top though.

**Comment by Heintz11** [comment]
@AJCStriker ya definitely will add one. This is just the main module setup.

**Comment by Zoosterbaan** [comment]
looks good to me, the LZ is kinda close to 2 enemy bases depending what enemy treat there will be expected small arms we will be good but .50 pickups is gonna screw us over

**Comment by AJCStriker** [comment]
@Zoosterbaan Could we come in from the side with mountain cover, low and fast to avoid taking contact from the bases?

There seems to be heavy terrain cover IVO the airstrip which could provide concealment for the aircraft?

**Comment by Zoosterbaan** [comment]
LZ suggestion: 
![2015-01-12_00002](https://cloud.githubusercontent.com/assets/10477999/5704706/2f4e3d5a-9a74-11e4-8387-d43d340e9a87.jpg)

**Comment by AJCStriker** [comment]
@Zoosterbaan the discussion has actually moved to landing the troops on the airfield using an air assault.

The marked LZ in the recon photos was for an airborne jump but it was not deemed viable. I don’t think it’s a good idea for us to hit the bases straight on, we can land at the airfield and then move out from there. 

You will also need to plan an additional flight plan for round trips to the LHD so we can ferry in the first team of engineers and their first line kit. It is my understanding that a second team of combat engineers will be coming in with watercraft near the end of the operation, but that the initial team of 3-4 will need to be brought onshore in a second airlift.=

**Comment by Zoosterbaan** [comment]
rgr ill hand out the flight plan as soon as we know the position of the LHD.

**Comment by AJCStriker** [comment]
You make a good point. I opened #14 to try and locate a position for the ship.

**Comment by rasolercrespo** [comment]
I think based on our discussion, this discussion is complete. I am therefore closing it down as I go ahead and start gathering the final information for a build product.
