### ISSUE TITLE
Add Pilot Load outs to box

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#21]

**Comment by rasolercrespo** [comment]
@AJCStriker you also need to add Archangel and Anvil loadouts, whichever they may be.

**Comment by rasolercrespo** [comment]
Please see #29 because these two are essentially one issue. They need to be added to the box, AND to the spawn/respawn init lines in the units for Headhunter, Anvil, Archangel and Spartan 7M (Medic).

**Comment by AJCStriker** [comment]
This is now complete but @Zoosterbaan fucked up.

We will need to get the new loadouts from them to update it, but they have provisionally been added, hence I am closing the issue.
