### ISSUE TITLE
Reduce AI Difficulty

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#22]
AI were super troopers during testing.

AI requires nerfing.

**Comment by AJCStriker** [comment]
@rasolercrespo asking you to take this one because i'm clocking off for tonight

**Comment by rasolercrespo** [comment]
@AJCStriker that's fine. I'll take a look at it.

**Comment by rasolercrespo** [comment]
@AJCStriker can I also get a github repo for ALiVE? Stratis.

**Comment by AJCStriker** [comment]
https://gist.github.com/AJCStriker/754265fb83d54e90e0af

**Comment by AJCStriker** [comment]
The arrays in init.sqf detail the skills as above.

**Comment by rasolercrespo** [comment]
SOLUTION: I changed the references in:

0 = [_valkovaGroup, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;
0 = [_valkovaGroup1, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;
0 = [_valkovaGroup2, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;
0 = [_valkovaGroup3, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;

to 

0 = [_valkovaBaseGroup, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;
0 = [_valkovaBaseGroup1, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;

and

0 = [_valkovaGroup, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;
0 = [_valkovaGroup1, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;
0 = [_valkovaGroup2, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;
0 = [_valkovaGroup3, [0.0250, 0.9, 0.3, 1.0, 0.7, 0.3, 0.5, 0.3, 0.9, 0.5]] call Zen_SetAISkill;

to

0 = [_valkovaBaseGroup2, "valkova_base_2", [20, 250], [0,360], 'limited', 'safe', true] spawn Zen_OrderInfantryPatrol;
0 = [_valkovaBaseGroup3, "valkova_base_2", [20, 250], [0,360], 'limited', 'safe', true] spawn Zen_OrderInfantryPatrol;

This should close this issue.
