### ISSUE TITLE
Close patrol distances on squads in the military bases and separate their spawn points.

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#26]

**Comment by rasolercrespo** [comment]
I closed the walk distance from one patrol group (10 to 25 m) and the other essentially within the base (from 1 to 3 m). I did that so the AI is not standing there and derping when we come in bullets blazing. I am closing this issue. Please check my work.

**Comment by rasolercrespo** [comment]
I had to fix their walking distances because the small ones within the base were making Zen framework error out. It should be good now. I used 20m to 60m.
