### ISSUE TITLE
Move the civilian routes to be tighter and patrol the town

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#27]

**Comment by rasolercrespo** [comment]
I didn't touch this at all. My hint to you would be to use more waypoints along the driving route for the buses. This helped me tremendously back when we were doing Ops in that one terrain map whose name I can't recall.

**Comment by rasolercrespo** [comment]
Panthera's road doesn't work great for route indexing, so Striker did his best. I am closing the issue.
