### ISSUE TITLE
Grenadier loadout isn't working

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#28]
By chance, I tried the loadouts on the Quartermaster and the Grenadier loadouts are wrong. 

1) Are they the most up to date?
2) Why does the SQF for Grenadier have a M249 PIP? :p 

I'm putting this here but the fix is real quick.

**Comment by AJCStriker** [comment]
Oges fucked up and reposted the new one online during our testing. There was also an issue with the FTL lacking a radio.

Both need correcting but the loadouts on the forum have been repaired.

**Comment by rasolercrespo** [comment]
I'll fix these and close the issue. You can inspect the loadouts for Infantry.

**Comment by rasolercrespo** [comment]
@AJCStriker, the infantry loadouts are fixed and implemented on respawn. This will solve #25 in part.
