### ISSUE TITLE
Archangel, Anvil and Headhunter Loadouts

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#29]
Archangel, Anvil and Headhunter loadouts are both:

1) Missing
2) Not implemented on spawn and respawn.

I have already taken care of all loadout issues for Spartan (Infantry).

**Comment by rasolercrespo** [comment]
CORRECTION: We have no Spartan 6M, aka we have no Medic loadout.

Just copy paste the init I used for the Infantry, and use it for everyone else. Piece o' cake.

**Comment by AJCStriker** [comment]
It is my understanding that Charlie will use the standard kit loads that Spartan put together, as will I.

Leaving this one open but removing the mission critical tag.

**Comment by rasolercrespo** [comment]
The loadouts are implemented and the Quarter Master is working.

I also fixed the tablet issue for the pilot.

This can be closed, I believe. Check my work, @AJCStriker.
