### ISSUE TITLE
Decide insertion method

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#3]
How are we going to insert? 

A) Takeoff from allied airfield
B) Helicopters
C) Spawn in the air

**Comment by rasolercrespo** [comment]
@Zoosterbaan and myself will work on this, with guidance from @AJCStriker

**Comment by Zoosterbaan** [comment]
Helicopter from the LHD

2015-01-10 19:05 GMT+01:00 Rafael A. Soler-Crespo <notifications@github.com>
:

**Comment by rasolercrespo** [comment]
As with #2, this discussion is done and can therefore be shifted to deciding its location in #14. I am closing it as I gather information for the initial build.
