### ISSUE TITLE
Military installation?

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#30]
These lines, I think, mean to spawn a static weapon:

// Spawn Military Installation
['valkova_base_2', 75, 'rhs_weap_pkt' ] call Zen_SpawnFortification;

If I am wrong, just close this issue. Else, if you meant to spawn a tank, the Object Name is: 

rhs_t80

**Comment by rasolercrespo** [comment]
We should remove this line, or comment it out, if it doesn't do anything. Pet peeve, just putting it out there in case it's actually important.

**Comment by AJCStriker** [comment]
It actually spawns a ring of defensive emplacements around the southern army base.

**Comment by rasolercrespo** [comment]
Got it. Then, I'll close this issue.

Good job by the way, that looks real nice.
