### ISSUE TITLE
Move the spawn for the squads in military bases?

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#32]
Some units spawn dead because they are spawning on top of things in the bases. Either we can move the spawns a bit, or we can just live with it and have a Zeus delete the killed units before we load the choppers. Not really a game breaker, just nitpicking the final details of the Operation.

**Comment by AJCStriker** [comment]
Let's go with Zeus. Saves a headache.

**Comment by rasolercrespo** [comment]
Sounds good to me. I'll close this issue.
