### ISSUE TITLE
Reduce the AI difficulty of the CQC units placed manually?

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#33]
I put down 6 units in the Op. 2 of them are near the ATC (couldn't get them to climb up -- too lazy to manually set them) and 4 of them are in the town near the airfield. I set their AI Skill to zero but I am worried they might still be too overpowered, so if possible, can we pass the Zen values/skill to those 6 guys? If not, is there a way to do it with Arma 3 commands/scripting?

I will be happy to do this if we can find a way to do it, but I don't have time right now to work on it.

**Comment by rasolercrespo** [comment]
Rod mentioned using Zen and a command such as:

_null = [east,"Militia"] call Zen_SetAISkill;

We can get it to work. We can give it a test tomorrow.

**Comment by AJCStriker** [comment]
I tried the preset strings already and it created terminators. I think the numbers array is a safer option.

**Comment by AJCStriker** [comment]
Reread this and yes that call works fine but I advise using the custom array instead of the string.

**Comment by rasolercrespo** [comment]
That's fine with me, as long as those guys on the floor I placed manually get their AI set by the custom array.
