### ISSUE TITLE
Personal Configurations Arsenal

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#36]
We need to create an arsenal that contains the following items only:

```
What you are authorized to change:
Your goggles slot (NO full face coverings or beards)
Your weapon primary optic (no thermals)
Your in game face, skin color, and voice (not everyone needs to look like me)
Your left arm patch
```

**Comment by rasolercrespo** [comment]
We'll delay this for now, unless I have some time to get to it. I'll work on it for the next op.

**Comment by rasolercrespo** [comment]
I'm reopening just so you can take a look, Striker. We won't implement this shit for this one though. Let's make sure this PBO is ready and send it out. Take a look at my 2 pull requests. Make sure you  merge them in the right order. >.<

The solution is HERE:

http://forums.unitedoperations.net/index.php/topic/23613-virtual-arsenal-restricting-items/

@AJCStriker
