### ISSUE TITLE
R3F Logistics System ALiVE Integration

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#4]
Charlie company are requesting the R3F Logistics system. It is an pretty solid system with comparatively few issues. It plugs into ALIVE well but requires a small modification to the script. 

Quoted from the BI Forums:
```
 try to add this line in R3F_LOG\objet_deplacable\relacher.sqf at line 12 :
Code:
[LOGIC_ALIVE,"updateObject",[R3F_LOG_joueur_deplace_objet]] call ALIVE_fnc_logistics;
```

**Comment by rasolercrespo** [comment]
We can give it a try, and correct as needed during ops construction.
