### ISSUE TITLE
How to save objects 

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#41]
Run this command in the debug console at the end of the operation and press server execute.

```
{ ["saveObject", [typeOf _x, getPos _x,  getDir _x]] call sock_rpc; } forEach (allMissionObjects "All");
```

**Comment by rasolercrespo** [comment]
Now:

{ ["saveObject", [typeOf _x, _x modelToWorld [0,0,0],  getDir _x]] call sock_rpc; } forEach (allMissionObjects "All");
