### ISSUE TITLE
Aviation Requirements

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#7]
@Zoosterbaan needs to add the requirements the aviation guys need from a script point of view.

ATM my list looks like:

* Igiload

**Comment by Zoosterbaan** [comment]
igiload and RAVLifter is all we need to transport ppl and equipment durring the missions

**Comment by AJCStriker** [comment]
Both IgiLoad and RAVLifter are currently deployed in the build so that should close #7.

If we need to add another aircraft to RAVLifter, for example the Pavehawk or Red Hammer Studios stuff then you should reopen this issue.=
