### ISSUE TITLE
Implement Respawns

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#8]
Someone from @23rd-gaming-division/s3-development needs to add the respawn point and ensure that players are able to respawn on the LHD with it. Respawn should take place after complete death from CSE.

**Comment by Oges03** [comment]
Are we respawning in a "can", or are the respawned personnel going to constitute a QRF for the remainder of the mission (highest ranking death takes charge and forms up the rest of the dead for the QRF like we did last OP)?

**Comment by AJCStriker** [comment]
@Oges03 Thinking we should probably let the dead form up on the LHD. For this op they can help the rear line elements with the second wave of landings.

**Comment by AJCStriker** [comment]
This is still a critical issue.

**Comment by rasolercrespo** [comment]
I have implemented a respawn. Please test it. With this, we can close the issue.
