### ISSUE TITLE
Mission storyline

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#9]
We will be using the area @AJCStriker has imaged in #2 

For now, the idea is to insert friendly units in the unimproved airfield and march east to west, clearing out the town and military bases in an effort to capture the peninsula for US Army use. Forces would consist of 2 x Squad and 2 x Fireteam. 1 x Squad would be present in each military base, 1 x Fireteam would be present in the town near the area (with civilians) and 1 x Fireteam would be present in the buildings north of the potential FOB.   Additionally, 1 x Armed Vehicle will be present in the military base on the hill.

**Comment by rasolercrespo** [comment]
We'd plan for Charlie Co. to build a FOB, and some minor roadblocks for the MSR, depending on resource availability.

**Comment by AJCStriker** [comment]
I think it would be necessary to have one person operate the watercraft to ship the vehicles onto shore. We need to bring some armored humvees and maybe some mild AA.

**Comment by rasolercrespo** [comment]
This will be handled by the WARNO, and we have a rough idea of what we want for building purposes. Thus, I'm closing this issue.
